retab (tab=4spaces)

diff --git a/build-openstack-debian-image b/build-openstack-debian-image
--- a/build-openstack-debian-image
+++ b/build-openstack-debian-image
@@ -1,10 +1,11 @@
 #!/bin/sh
+# tab = 4 spaces
 
 set -e
 
 # Parse input parameters
 usage() {
-	echo "Usage: $0 --release|-r <jessie|wheezy> [options]
+    echo "Usage: $0 --release|-r <jessie|wheezy> [options]
 Options are:
  --minimal|-m
  --debootstrap-url|-u <debootstrap-mirror> (default: http://http.debian.net/debian)
@@ -16,138 +17,138 @@ Options are:
  --automatic-resize-space|-ars <suplementary-space> (default: 50M)
  --password|-p <root-password> (dangerous option: avoid it if possible)
 For more info: man $0"
-	exit 1
+    exit 1
 }
 
 EXTRA=yes
 for i in $@ ; do
-	case "${1}" in
-	"--extra-packages"|"-e")
-		if [ -z "${2}" ] ; then
-			echo "No parameter defining the extra packages"
-			usage
-		fi
-		EXTRA_PACKAGES=${2}
-		shift
-		shift
-	;;
-	"--debootstrap-url"|"-u")
-		if [ -z "${2}" ] ; then
-			echo "No parameter defining the debootstrap URL"
-			usage
-		fi
-		DEB_MIRROR=${2}
-		shift
-		shift
-	;;
-	"--minimal"|"-m")
-		EXTRA=no
-		shift
-	;;
-	"--automatic-resize"|"-ar")
-		AUTOMATIC_RESIZE=yes
-		shift
-	;;
-	"--automatic-resize-space"|"-ars")
-		if [ -z "${2}" ] ; then
-			echo "No parameter defining the suplementary space"
-			usage
-		fi
-		AUTOMATIC_RESIZE_SPACE=${2}
-		shift
-		shift
-	;;
-	"--image-size"|"-is")
-		if [ -z "${2}" ] ; then
-			echo "No parameter defining the image size"
-			usage
-		fi
-		IMAGE_SIZE=${2}
-		shift
-		shift
-	;;
-	"--hook-script"|"-hs")
-		if [ -z "${2}" ] ; then
-			echo "No parameter defining the hook script"
-			usage
-		fi
-		if ! [ -x "${2}" ] ; then
-			echo "Hook script not executable"
-		fi
-		HOOK_SCRIPT=${2}
-		shift
-		shift
-	;;
-	"--sources.list-mirror"|"-s")
-		if [ -z "${2}" ] ; then
-			echo "No parameter defining the hook script"
-			usage
-		fi
-		SOURCE_LIST_MIRROR=${2}
-		shift
-		shift
-	;;
-	"--release"|"-r")
-		if [ "${2}" = "wheezy" ] || [ "${2}" = "jessie" ] ; then
-			RELEASE=${2}
-			shift
-			shift
-		else
-			echo "Release not recognized."
-			usage
-		fi
-	;;
-	"--password"|"-p")
-		if [ -z "${2}" ] ; then
-			echo "No parameter defining the root password"
-		fi
-		ROOT_PASSWORD=${2}
-		shift
-		shift
-	;;
-	*)
-	;;
-	esac
+    case "${1}" in
+    "--extra-packages"|"-e")
+        if [ -z "${2}" ] ; then
+            echo "No parameter defining the extra packages"
+            usage
+        fi
+	EXTRA_PACKAGES=${2}
+	shift
+	shift
+    ;;
+    "--debootstrap-url"|"-u")
+        if [ -z "${2}" ] ; then
+	    echo "No parameter defining the debootstrap URL"
+	    usage
+	fi
+	DEB_MIRROR=${2}
+	shift
+	shift
+    ;;
+    "--minimal"|"-m")
+        EXTRA=no
+	shift
+    ;;
+    "--automatic-resize"|"-ar")
+        AUTOMATIC_RESIZE=yes
+	shift
+    ;;
+    "--automatic-resize-space"|"-ars")
+        if [ -z "${2}" ] ; then
+	    echo "No parameter defining the suplementary space"
+	    usage
+	fi
+	AUTOMATIC_RESIZE_SPACE=${2}
+	shift
+	shift
+    ;;
+    "--image-size"|"-is")
+	if [ -z "${2}" ] ; then
+	    echo "No parameter defining the image size"
+	    usage
+	fi
+	IMAGE_SIZE=${2}
+	shift
+	shift
+    ;;
+    "--hook-script"|"-hs")
+	if [ -z "${2}" ] ; then
+	    echo "No parameter defining the hook script"
+	    usage
+	fi
+	if ! [ -x "${2}" ] ; then
+	    echo "Hook script not executable"
+	fi
+	HOOK_SCRIPT=${2}
+	shift
+	shift
+    ;;
+    "--sources.list-mirror"|"-s")
+	if [ -z "${2}" ] ; then
+	    echo "No parameter defining the hook script"
+	    usage
+	fi
+	SOURCE_LIST_MIRROR=${2}
+	shift
+	shift
+    ;;
+    "--release"|"-r")
+	if [ "${2}" = "wheezy" ] || [ "${2}" = "jessie" ] ; then
+	    RELEASE=${2}
+	    shift
+	    shift
+	else
+	    echo "Release not recognized."
+	    usage
+	fi
+    ;;
+    "--password"|"-p")
+	if [ -z "${2}" ] ; then
+	    echo "No parameter defining the root password"
+	fi
+	ROOT_PASSWORD=${2}
+	shift
+	shift
+    ;;
+    *)
+    ;;
+    esac
 done
 
 if [ -z "${RELEASE}" ] ; then
-	echo "Release not recognized: please specify the -r parameter."
-	usage
+    echo "Release not recognized: please specify the -r parameter."
+    usage
 fi
 if [ -z "${DEB_MIRROR}" ] ; then
-	DEB_MIRROR=http://http.debian.net/debian
+    DEB_MIRROR=http://http.debian.net/debian
 fi
 if [ -z "${EXTRA_PACKAGES}" ] ; then
-	EXTRA_PACKAGES=bash-completion,joe,most,screen,less,vim,bzip2
+    EXTRA_PACKAGES=bash-completion,joe,most,screen,less,vim,bzip2
 fi
 if [ -z "${SOURCE_LIST_MIRROR}" ] ; then
-	SOURCE_LIST_MIRROR=http://http.debian.net/debian
+    SOURCE_LIST_MIRROR=http://http.debian.net/debian
 fi
 if [ -z "${IMAGE_SIZE}" ] ; then
-	IMAGE_SIZE=1
+    IMAGE_SIZE=1
 fi
 if [ -z "${AUTOMATIC_RESIZE_SPACE}" ] ; then
-	AUTOMATIC_RESIZE_SPACE=50
+    AUTOMATIC_RESIZE_SPACE=50
 fi
 
 NEEDED_PACKAGES=sudo,adduser,locales,extlinux,openssh-server,linux-image-amd64,euca2ools,file,kbd
 if [ "${RELEASE}" = "jessie" ] ; then
-	NEEDED_PACKAGES=${NEEDED_PACKAGES},cloud-init,cloud-utils,cloud-initramfs-growroot
+    NEEDED_PACKAGES=${NEEDED_PACKAGES},cloud-init,cloud-utils,cloud-initramfs-growroot
 else
-	# These are needed by cloud-init and friends, and since we don't want backports of them,
-	# but just normal packages from Wheezy, we resolve dependencies by hand, prior to using
-	# apt-get -t wheezy-backports install cloud-init cloud-utils cloud-initramfs-growroot
-	NEEDED_PACKAGES=${NEEDED_PACKAGES},python,python-paramiko,python-argparse,python-cheetah,python-configobj,python-oauth,python-software-properties,python-yaml,python-boto,python-prettytable,initramfs-tools,python-requests
+    # These are needed by cloud-init and friends, and since we don't want backports of them,
+    # but just normal packages from Wheezy, we resolve dependencies by hand, prior to using
+    # apt-get -t wheezy-backports install cloud-init cloud-utils cloud-initramfs-growroot
+    NEEDED_PACKAGES=${NEEDED_PACKAGES},python,python-paramiko,python-argparse,python-cheetah,python-configobj,python-oauth,python-software-properties,python-yaml,python-boto,python-prettytable,initramfs-tools,python-requests
 fi
 
 if [ ${EXTRA} = "no" ] ; then
-	PKG_LIST=${NEEDED_PACKAGES}
+    PKG_LIST=${NEEDED_PACKAGES}
 else
-	PKG_LIST=${NEEDED_PACKAGES},${EXTRA_PACKAGES}
+    PKG_LIST=${NEEDED_PACKAGES},${EXTRA_PACKAGES}
 fi
 if ! [ `whoami` = "root" ] ; then
-	echo "You have to be root to run this script"
-	exit 1
+    echo "You have to be root to run this script"
+    exit 1
 fi
 FILE_NAME=debian-${RELEASE}-7.0.0-3-amd64
 AMI_NAME=${FILE_NAME}.raw
@@ -171,22 +172,22 @@ install-mbr ${AMI_NAME}
 RESULT_KPARTX=`kpartx -av ${AMI_NAME} 2>&1`
 
 if echo "${RESULT_KPARTX}" | grep "^add map" ; then
-	LOOP_DEVICE=`echo ${RESULT_KPARTX} | cut -d" " -f3`
-	echo "kpartx mounted using: ${LOOP_DEVICE}"
+    LOOP_DEVICE=`echo ${RESULT_KPARTX} | cut -d" " -f3`
+    echo "kpartx mounted using: ${LOOP_DEVICE}"
 else
-	echo "It seems kpartx didn't mount the image correctly: exiting."
-	exit 1
+    echo "It seems kpartx didn't mount the image correctly: exiting."
+    exit 1
 fi
 
 cleanup(){
-	[ ! -d "${MOUNT_DIR}" ] && return
-	echo
-	echo "error, umounting $MOUNT_DIR"
-	chroot ${MOUNT_DIR} umount /proc || true
-	chroot ${MOUNT_DIR} umount /sys || true
-	umount ${MOUNT_DIR}
-	rmdir ${MOUNT_DIR}
-	kpartx -d ${AMI_NAME}
+    [ ! -d "${MOUNT_DIR}" ] && return
+    echo
+    echo "error, umounting $MOUNT_DIR"
+    chroot ${MOUNT_DIR} umount /proc || true
+    chroot ${MOUNT_DIR} umount /sys || true
+    umount ${MOUNT_DIR}
+    rmdir ${MOUNT_DIR}
+    kpartx -d ${AMI_NAME}
 }
 trap "cleanup" EXIT TERM INT
 
@@ -209,7 +210,7 @@ debootstrap --verbose \
 # # # # # # # # # # # # # # # # # #
 # Setup default root password to what has been set on the command line
 if [ -n "${ROOT_PASSWORD}" ] ; then
-	chroot ${MOUNT_DIR} sh -c "echo root:${ROOT_PASSWORD} | chpasswd"
+    chroot ${MOUNT_DIR} sh -c "echo root:${ROOT_PASSWORD} | chpasswd"
 fi
 
 # Otherwise, we have a huge backdoor, since the root password
@@ -244,19 +245,19 @@ pci_hotplug
 
 # Enable bash-completion by default
 if [ ${EXTRA} = "yes" ] ; then
-	echo "# enable bash completion in interactive shells
+    echo "# enable bash completion in interactive shells
 if ! shopt -oq posix; then
-  if [ -f /usr/share/bash-completion/bash_completion ]; then
-    . /usr/share/bash-completion/bash_completion
-  elif [ -f /etc/bash_completion ]; then
-    . /etc/bash_completion
-  fi
+    if [ -f /usr/share/bash-completion/bash_completion ]; then
+        . /usr/share/bash-completion/bash_completion
+    elif [ -f /etc/bash_completion ]; then
+        . /etc/bash_completion
+    fi
 fi" >>${MOUNT_DIR}/etc/bash.bashrc
 
-	# No clear for the tty1 console
-	sed -i "s#1:2345:respawn:/sbin/getty 38400 tty1#1:2345:respawn:/sbin/getty --noclear 38400 tty1#" ${MOUNT_DIR}/etc/inittab
+    # No clear for the tty1 console
+    sed -i "s#1:2345:respawn:/sbin/getty 38400 tty1#1:2345:respawn:/sbin/getty --noclear 38400 tty1#" ${MOUNT_DIR}/etc/inittab
 
-	chroot ${MOUNT_DIR} apt-get install -y locales-all
+    chroot ${MOUNT_DIR} apt-get install -y locales-all
 fi
 
 # Turn off console blanking which is *very* annoying
@@ -300,7 +301,7 @@ echo "deb ${SOURCE_LIST_MIRROR} ${RELEASE} main
 deb-src ${SOURCE_LIST_MIRROR} ${RELEASE} main" >${MOUNT_DIR}/etc/apt/sources.list
 
 if [ "${RELEASE}" = "wheezy" ] ; then
-	echo "deb ${SOURCE_LIST_MIRROR} wheezy-updates main
+    echo "deb ${SOURCE_LIST_MIRROR} wheezy-updates main
 deb-src ${SOURCE_LIST_MIRROR} wheezy-updates main
 deb http://security.debian.org/ wheezy/updates main
 deb-src http://security.debian.org/ wheezy/updates main
@@ -314,7 +315,7 @@ chroot ${MOUNT_DIR} apt-get update
 # Setup cloud-init, cloud-utils and cloud-initramfs-growroot
 # These are only available from backports in Wheezy
 if [ "${RELEASE}" = "wheezy" ] ; then
-	chroot ${MOUNT_DIR} apt-get -t wheezy-backports install cloud-init cloud-utils cloud-initramfs-growroot -y
+    chroot ${MOUNT_DIR} apt-get -t wheezy-backports install cloud-init cloud-utils cloud-initramfs-growroot -y
 fi
 
 # For OpenStack, we would like to use Ec2 and no other API
@@ -346,9 +347,9 @@ extlinux --install ${MOUNT_DIR}
 ### HOOK SCRIPT ###
 ###################
 if [ -x ${HOOK_SCRIPT} ] ; then
-	export BODI_CHROOT_PATH=${MOUNT_DIR}
-	export BODI_RELEASE=${RELEASE}
-	${HOOK_SCRIPT}
+    export BODI_CHROOT_PATH=${MOUNT_DIR}
+    export BODI_RELEASE=${RELEASE}
+    ${HOOK_SCRIPT}
 fi
 
 ##########################
@@ -356,8 +357,8 @@ fi
 ##########################
 
 cleanup(){
-	# refine cleanup everything was ok
-	echo "Finished."
+    # refine cleanup everything was ok
+    echo "Finished."
 } 
 
 chroot ${MOUNT_DIR} umount /proc || true
@@ -367,27 +368,27 @@ tune2fs -j /dev/mapper/${LOOP_DEVICE}
 fsck.ext3 -f /dev/mapper/${LOOP_DEVICE} || true
 
 if [ "${AUTOMATIC_RESIZE}" = "yes" ] ; then
-	resize2fs -M /dev/mapper/${LOOP_DEVICE}
-	FS_BLOCKS=`tune2fs -l /dev/mapper/${LOOP_DEVICE} | awk '/Block count/{print $3}'`
-	WANTED_SIZE=`expr $FS_BLOCKS '*' 4 '/' 1024 + ${AUTOMATIC_RESIZE_SPACE}` # Add ${AUTOMATIC_RESIZE_SPACE}M
-	resize2fs /dev/mapper/${LOOP_DEVICE} ${WANTED_SIZE}M
+    resize2fs -M /dev/mapper/${LOOP_DEVICE}
+    FS_BLOCKS=`tune2fs -l /dev/mapper/${LOOP_DEVICE} | awk '/Block count/{print $3}'`
+    WANTED_SIZE=`expr $FS_BLOCKS '*' 4 '/' 1024 + ${AUTOMATIC_RESIZE_SPACE}` # Add ${AUTOMATIC_RESIZE_SPACE}M
+    resize2fs /dev/mapper/${LOOP_DEVICE} ${WANTED_SIZE}M
 
-	FINAL_FS_BLOCKS=`tune2fs -l /dev/mapper/${LOOP_DEVICE} | awk '/Block count/{print $3}'`
-	FINAL_IMG_SIZE=`expr '(' $FINAL_FS_BLOCKS + 258 ')' '*' 4 '/' 1024` # some blocks for mbr and multiple block size (4k)
+    FINAL_FS_BLOCKS=`tune2fs -l /dev/mapper/${LOOP_DEVICE} | awk '/Block count/{print $3}'`
+    FINAL_IMG_SIZE=`expr '(' $FINAL_FS_BLOCKS + 258 ')' '*' 4 '/' 1024` # some blocks for mbr and multiple block size (4k)
 fi
 
 kpartx -d ${AMI_NAME}
 rmdir ${MOUNT_DIR}
 
 if [ "${AUTOMATIC_RESIZE}" = "yes" ] ; then
-	# Rebuild a smaller partition table
-	parted -s ${AMI_NAME} rm 1
-	parted -s ${AMI_NAME} mkpart primary ext3 1Mi ${FINAL_IMG_SIZE}Mi
-	parted -s ${AMI_NAME} set 1 boot on
+    # Rebuild a smaller partition table
+    parted -s ${AMI_NAME} rm 1
+    parted -s ${AMI_NAME} mkpart primary ext3 1Mi ${FINAL_IMG_SIZE}Mi
+    parted -s ${AMI_NAME} set 1 boot on
 
-	# Add 2M for the 1M at the beginning of the partition and some additionnal space 
-	truncate -s `expr 3 + ${FINAL_IMG_SIZE}`M ${AMI_NAME}
-	install-mbr ${AMI_NAME}
+    # Add 2M for the 1M at the beginning of the partition and some additionnal space 
+    truncate -s `expr 3 + ${FINAL_IMG_SIZE}`M ${AMI_NAME}
+    install-mbr ${AMI_NAME}
 fi
 
 qemu-img convert -c -f raw ${AMI_NAME} -O qcow2 ${QCOW2_NAME}
